notch8/adventist_knapsack

- app/indexers/hyrax/file_set_indexer_decorator.rb
- app/models/file_set_decorator.rb
When running a job that attached a file set we received errors because the private methods were missing from this project. They exist in an adventist override: https://github.com/scientist-softserv/adventist-dl/blob/main/app/indexers/hyrax/file_set_indexer.rb
> 🐛 Fix for human_readable_label_name not defined

- app/controllers/catalog_controller_decorator.rb
This commit will remove or add fields to the Blacklight configuration based on what is currently is in Adventist production.  It builds off of Hyku's `CatalogController.configure_blacklight`.
In irb we're getting a similar object when calling `CatalogController.configure_blacklight`.  It's not exactly the same because configurations in Hyku was updated and I'm sure we'll catch any errors as we go.
```rb
irb(main):001:0> CatalogController.configure_blacklight
=> #<Blacklight::Configuration http_method=:post, solr_path="select", default_solr_params={:qt=>"search", :rows=>10, :qf=>"creator_tesim resource_type_tesim abstract_tesim presented_at_tesim location_tesim event_date_tesim part_of_tesim editor_tesim publisher_tesim place_of_publication_tesim date_published_tesim …
```
> 🧹 Override `CatalogController`

- app/controllers/hyku_knapsack/pages_controller.rb
- app/models/content_block_decorator.rb
- config/routes.rb
This commit will get the resources route working. It will also add a HykuKnapsack::PagesController which inherits from Hyrax::PagesController so the route won't throw a namespace error.  Further down the line, we needed to decorate the ContentBlock model to add the resources key.  I am doing this with no change to Hyku although we may want to add the `#name_registry` method to Hyku as a convenience for overrides since we can't add to a frozen hash.
ref: https://github.com/scientist-softserv/adventist-dl/issues/556
This gets the /resources route to load but there are problems in erb files down the line that are currently being addressed.  In an effort to not step on toes and letting the scope of this PR get too big, I am stopping here.
> 🧹 Get resources route working

- config/initializers/knapsack_authorities.rb
We favor the use of `HykuKnapsack::Engine.root` instead of using `'..'` to get us to into the root of the engine because it is more sturdy.
> 🧹 Improve relative path

- app/forms/hyrax/form_terms_decorator.rb
- lib/hyku_knapsack/engine.rb
Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/585
Refs #issuenumber
<details>
</details>
> 🧹 Add FormTermsDecorator

- app/views/hyrax/base/show.html.erb
Refs [#572
](https://github.com/scientist-softserv/adventist-dl/issues/572)
Work show page did not include action buttons
Buttons appear and are right-justified, as they previously were. (Note that for styling to match, it would need to include https://github.com/scientist-softserv/adventist_knapsack/pull/20
<details>
</details>
> Show actions

- .gitmodules
In discussion with the team, we're to be using that branch.  This change does two things:
1. Points to the latest commit on that branch.
2. Specifies the branch we're using.
At somepoint, we'll want to move away from the branch to reference "main" but that's a day on the hopefully near horizon.
> 🧹 Specify submodule branch for hyrax-webapp

- Dockerfile
- config/initializers/iiif_print.rb
Adds tesseract eng_best installation instructions to the Dockerfile. Not doing so was the reason the CreateDerivativesJobs would fail.
Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/581
Before this PR end_best.traineddata did not exists in /usr/shared/tessdata
> ⚙️ Install tesseract eng_best

- app/views/layouts/hyrax.html.erb
- app/views/shared/_footer.html.erb
- lib/hyku_knapsack/engine.rb
We are discovering that view paths are not consistent across different controllers.  Prior to this PR, for some of the controllers, we had a view path of:
- `/app/samvera/app/views/`
- `/app/samvera/hyrax-webapp/app/views/`
And for others, in particularly the Works controllers, we had:
- `/app/samvera/hyrax-webapp/app/views/`
- `/app/samvera/app/views/`
With this commit, we're taking a hammer to the view paths to mash them into shape.
> Load view paths on display

- spec/features/splash_spec.rb
Prior to this commit the diff was as follows:
```
❯ diff spec/features/splash_spec.rb hyrax-webapp/spec/features/splash_spec.rb
3c3,4
< RSpec.describe "The splash page", multitenant: true do
---
> # NOTE: If want to run spec in broweser, you have to set "js: true"
> RSpec.describe "The splash page", type: :feature, clean: true, multitenant: true do
4a6,7
>     original = ENV['HYKU_ADMIN_ONLY_TENANT_CREATION']
>     ENV['HYKU_ADMIN_ONLY_TENANT_CREATION'] = "true"
8a12
>     ENV['HYKU_ADMIN_ONLY_TENANT_CREATION'] = original
11c15
<   xit "shows the page, displaying the Hyku version" do
---
>   it "shows the page, displaying the Hyku version" do
19c23
<     expect(page).to have_content("© Adventist Digital Library 2021")
---
>     expect(page).to have_content("Hyku v#{Hyku::VERSION}")
``` …
> 🧹 Fix spec/features/spash_spec.rb

- spec/forms/hyrax/generic_work_form_decorator_spec.rb
Prior to this commit the Knapsace generic_work_form_spec had a test for terms
that was not part of the Hyku.  We introduce these differences through our
decoration in ./app/forms/hyrax/generic_work_form_decorator.rb
To reflect the existence of the decorator and not have a duplicate file
that future us would need to synchronize with Hyku, I've moved the file
and winnowed it down to reflect the specific changes.
I also needed to add three new properties to the spec as it reflects
upstream changes in Hyku (e.g. `access_right` `alternative_title`
`rights_notes`)
<details>
<summary>Diff of filein Hyku and Knapsack</summary>
```
❯ diff spec/forms/hyrax/generic_work_form_spec.rb hyrax-webapp/spec/forms/hyrax/generic_work_form_spec.rb
26,43d25
<   describe '.terms' do
<     it 'returns an array …
```
> 🧹 Rename generic_work_form_spec to reflect decoration

- spec/forms/hyrax/image_form_decorator_spec.rb
Prior to this commit the Knapsace image_form_spec had a test for terms
that was not part of the Hyku.  We introduce these differences through our
decoration in ./app/forms/hyrax/image_form_decorator.rb
To reflect the existence of the decorator and not have a duplicate file
that future us would need to synchronize with Hyku, I've moved the file
and winnowed it down to reflect the specific changes.
I also needed to add three new properties to the spec as it reflects
upstream changes in Hyku (e.g. `access_right` `alternative_title`
`rights_notes`)
<details>
<summary>Diff of filein Hyku and Knapsack</summary>
```
❯ diff spec/forms/hyrax/image_form_spec.rb hyrax-webapp/spec/forms/hyrax/image_form_spec.rb
27,44d26
<   describe '.terms' do
<     it 'returns an array of inherited and custom …
```
> 🧹 Rename image_form_spec to reflect decoration

- docker-compose.yml
we need to compile the worker target and not the web target. they are similar images but the cmd is different.
> try to get worker to actually run when we start it

- config/initializers/bulkrax.rb
- spec/models/bulkrax/csv_entry_spec.rb
This commit includes two things:
1. Favor Bulkrax::EntrySpecHelper provided by Bulkrax (for which the
removed code was a prototype).
2. Use the existing spec to determine what the default work type should
be (instead of relying on a random assignment based on the first
element of the registered curation concerns)
And from this commit, we have a passing test!
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/538
- https://github.com/samvera-labs/bulkrax/pull/726
- https://github.com/samvera-labs/bulkrax/pull/719
- https://github.com/samvera-labs/bulkrax/pull/742
- https://github.com/samvera/hyku/pull/1811
> 🐛 Fix bug regarding assumed default work type

- spec/search_builders/adv_search_builder_spec.rb
I encourage you to read the code comments, reproduced here:
> Yes there's a duplicate for add_access_controls_to_solr_params; but
> that does not appear to be causing a problem like the duplication and
> order of the now removed additional :add_advanced_parse_q_to_solr,
> :add_advanced_search_to_solr filters.  Those existed in their current
> position and at the end of the array.
>
> When we had those duplicates, the :add_advanced_parse_q_to_solr
> obliterated the join logic for files.
>
> <2023-10-04 Wed> Oh how I wish I wrote a bit more back in the day.
> But alas, I didn't.  So I must rebuild that context.  Looking at the
> ":add_advanced_parse_q_to_solr obliterated the join logic" fragment,
> I'm assuming that what I meant was "I think that the
> …
> 🧹 Fix spec to reflect new order of processing

- app/models/concerns/slug_bug.rb
- config/initializers/slug_override.rb
- spec/config/initializers/slug_override_spec.rb
The [following code in Hyrax v3.5.0][1] is managing the delete via the
`Hyrax::Transactions` functionality.  The code is as follows:
```ruby
def delete(resource:)
af_object = ActiveFedora::Base.new
af_object.id = resource.id
af_object.delete
resource
end
```
The primary problem we're encountering is that this instantiates a bare
bones `ActiveFedora::Base` object that has an ID, but no other
properties (in particular the slug, which is the SolrDocument's ID).
This commit repurposes the logic of reindexing when we add/remove an
AARK_ID.  Important is that we attempt deletes both the `id` in
SOLR (which is the Fedora slug value) and delete on the
`fedora_id_ssi` (which is the `resource.id` from above).
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/567
[1]: …
> 🐛 Fix slug based deletion via Hyrax::Transactions

- app/controllers/catalog_controller_decorator.rb
- lib/hyku_knapsack/engine.rb
- spec/hyku_knapsack/engine_spec.rb
Prior to this change, assuming my default translation was "en" when I
called the following—`I18n.t('dog_biscuits.fields.date_issued')`—I would
get `Translation missing: en.dog_biscuits.fields.date_issued`.
We had added DogBiscuits into that path but we had not reloaded the
back-end.
Further, the catalog controller was no longer doing useful work.  The
`Rails.root` is `hyrax-webapp`; which would already be working.  For
more on this anti-pattern, see [Potential Issues Around Knapsack and Rails.root][1].
With this change, I have a small test to verify that dog biscuits
translations are in fact loaded.
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/611
- https://github.com/scientist-softserv/adventist-dl/issues/227
- …
> 🐛 Ensure knapsack translations are first choice

- app/controllers/catalog_controller_decorator.rb
- app/helpers/hyku_knapsack/application_helper.rb
- lib/hyku_knapsack/engine.rb
- spec/helpers/hyku_knapsack/application_helper_spec.rb
1e14e36bc4937769fd8ccde4306ac5125dcd3b0b
In the pre-knapsack Adventist, the IIIF Print gem overwrote :
`app/views/catalog/_index_header_list_default.html.erb` and the
Adventist Hyku instance did not have that view.
However with the upgrade to the latest Hyku version via Knapsack, that
Hyku overrided Hyrax's view.  And due to view_path issues, we favor the
Hyku instance.
The newer Hyku view override leverages a method that we in the
knapsack (and later in IIIF Print) can extend to inject the parent_query
and query parameter necessary for OCR highlighting.
Below is a *diff of the files in Knapsack's Hyku and IIIF Print*.  I
have not resolved all of these things but am close:
Note that when 'q' is present AND `document.any_highlighting?` is true
we want to pass the param as "parent_query". …
> Add app helper for ocr highlighting

- app/assets/stylesheets/adl-overrides/about-section.scss
- app/assets/stylesheets/adl-overrides/adl-overrides.scss
- app/views/adl/_about_section.html.erb
- app/views/hyrax/admin/appearances/_default_fonts_form.html.erb
- app/views/shared/_appearance_styles.html.erb
This goes beyond handling the "missing collections" mentioned in the ticket (which weren't actually missing... they only appear for tenant 'adl'), and addresses multiple homepage issues:
- remove flex from layout of content in body
- fix font of about section text to respect text selection
- add TODO comment, and comment out dynamic text link color which was not working correctly
Refs:
- https://github.com/scientist-softserv/adventist-dl/issues/593
Main page layout did not match current.
- Fixes layout for about text and collections
- Font text color is correct
<details>
</details>
> Fix homepage layout

- app/views/records/edit_fields/_publication_status.html.erb
- app/views/records/show_fields/_publication_status.html.erb
Prior to this commit, we specified that publication_status was a
singular value.  However that broke the general paradigm that most all
Hyrax model properties are multi-value.
What happened was that we would submit `collection[publication_status]`
which was ignored.  When we submit `collection[publication_status][]`
then the property value persists.
We also needed to consider how we'd translate the drop-down value to a
human readable value.  That is done in the corresponding show_fields
page.
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/620
> 🐛 Render publication_status as multi-value

- app/views/records/show_fields/_official_url.html.erb
Prior to this commit, because we did not have an official_url partial we
fellback on using the default renderer.
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/620
- https://github.com/scientist-softserv/adventist-dl/issues/615
<details aria-hidden>
<summary>Before Change</summary>
</details>
<details aria-hidden>
<summary>After Change</summary>
</details>
> 🐛 Add official_url show partial

- app/controllers/catalog_controller_decorator.rb
- spec/controllers/catalog_controller_decorator_spec.rb
In looking at the responses, Solr was complaining about a missing
spellcheck.dictionary for contributor.
To get this working, we removed the `spellcheck.dictionary` declaration.
One observation we had is that matches are now only made when we type a
significant number of characters (or 2 words, we don't know what).
An observed ongoing issue is that we're only finding exact matches.
Related:
- https://github.com/scientist-softserv/adventist-dl/issues/623
- https://github.com/scientist-softserv/adventist-dl/issues/622
Co-authored-by: LaRita Robinson <larita@scientist.com>
> 🐛 Fix add to collection by removing spellcheck

- app/models/adventist_metadata.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- app/views/journal_articles/edit_fields/_default.html.temp.erb
- app/views/records/edit_fields/_abstract.html.erb
- app/views/records/edit_fields/_date_created.html.erb
- config/locales/dog_biscuits.en.yml
Ref:
- https://github.com/scientist-softserv/adventist-dl/issues/632 Related to:
- https://github.com/scientist-softserv/adventist_knapsack/pull/77
Property date_created was defined inconsistently, which broke creation and editing of Image and GenericWork types.
This pull request adds a partial with a date picker for date_created and removes `multiple: false` from the definition for GenericWork and Image work types.
Additionally, several unused view partials are being removed, as they were in the wrong path location and would never be hit.
Refs
- #issuenumber
<details>
</details>
> 🐛 Make date created consistent

- app/forms/hyrax/conference_item_form.rb
- app/forms/hyrax/dataset_form.rb
- app/forms/hyrax/exam_paper_form.rb
- app/forms/hyrax/journal_article_form.rb
- app/forms/hyrax/published_work_form.rb
- app/forms/hyrax/thesis_form.rb
- config/initializers/dog_biscuits.rb
- spec/forms/hyrax/conference_item_form_spec.rb
- spec/forms/hyrax/dataset_form_spec.rb
- spec/forms/hyrax/exam_paper_form_spec.rb
- spec/forms/hyrax/generic_work_form_decorator_spec.rb
- spec/forms/hyrax/image_form_decorator_spec.rb
- spec/forms/hyrax/journal_article_form_spec.rb
- spec/forms/hyrax/published_work_form_spec.rb
- spec/forms/hyrax/thesis_form_spec.rb
Ref:
- https://github.com/scientist-softserv/adventist-dl/issues/627
Only Image and GenericWork types had correct required terms
All work types require only title and rights statement.
<details>
**Before:**
**After:**
</details>
> 🐛 Require only title and rights_statement

- app/forms/hyrax/forms/collection_form_decorator.rb
- spec/forms/hyrax/forms/collection_form_decorator_spec.rb
The inline comments explain best:
> As part of [PR 87][87] we have attempted to rid the collection form of
> the alternative_title (to deal with the conflicting predicate for
> slugs).  However, it is declared by way of
> `Hyrax::Forms::CollectionForm.delegate(:alternative_title, to: > :model)`
>
> Which means that we cannot rely on `remove_method` to tidy this up.
> Instead we declare the method (thus obliterating the delegation).
> We then use Ruby's `undef_method` which instructs the object to no
> longer `respond_to` the undefined method.  See the tests for
> clarification.
Further, I've discovered that re-using a decorator that was declared in
Hyku resulted in the Knapsack decorator not working; hence the rename.
Related to:
- …
> 🐛 Remove CollectionForm#alternative_title

- app/services/iiif_print/manifest_builder_service_behavior_decorator.rb
This commit will adjust the #rendering for maninfests to render a PDF download option for UV.  After the upgrade, IiifManifestPresenters don't seem to have the file_set_presenters we're looking for anymore.  We instead instantiate a Hyrax presenter which does have the needed file_set_presenters.
Ref:
- https://github.com/scientist-softserv/adventist-dl/issues/637
PDF works did not render a download option in the UV.
PDF works now will render a download option in the UV.
> 🐛 Fix UV download option for PDFs

- ops/staging-deploy.tmpl.yaml
Deploying to staging is failing with the error message: '3 insufficient cpu, 3 insufficient memory'. Maybe increasing the resources will help.
> :broom: Increase resources for staging

- app/views/hyrax/base/_attribute_rows.html.erb
When using the `#attribute_to_html` method, passing in the `render_as: :date` argument seem to sometimes cause invalid dates.  When the string is 11/08/2023, it gets parsed as August 8th, 2023.  This is a problem when you have a date like 11/13/2023, because there is no 13th month.
Ref:
- https://github.com/scientist-softserv/adventist-dl/issues/641
> 🐛 Fix invalid date error

- app/presenters/hyku/work_show_presenter_decorator.rb
- app/views/hyrax/base/_attribute_rows.html.erb
In the non knapsack app, the part of label was called "Periodical" for Journal Article work types. For the sake of consistency, the client would like to keep it this way.
Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/658
Adventist proper had a conditional in the [attribute_rows partial](https://github.com/scientist-softserv/adventist-dl/blob/92879b9c2c8e48c410ff4c8918019f8a8fd39607/app/views/hyrax/journal_articles/_attribute_rows.html.erb#L16-L20) to change the display label. This conditional no longer exists in adventist knapsack, so the fix was to add a label. 
We need to bring back a conditional label. For example, Generic Work's part of would now say Periodical. It seems as though that label should only apply to Article work types. …
> 🎁 Work show pg: Display Part Of as Periodical for Journal Articles

- .github/workflows/build-test-lint.yaml
This commit will update the hyrax-webapp submodule where we move the `#solr_document` method from private to public.  The method being private was causing a crash in the Universal Viewer.  As per Hyrax, the method should have been public in the first place.
Ref:
- https://github.com/samvera/hyku/commit/dbe996e71afa63a5ba8f68f55e4c50ed25d3729d
- https://github.com/samvera/hyrax/blob/b334e186e77691d7da8ed59ff27f091be1c2a700/app/presenters/hyrax/file_set_presenter.rb#L10
- https://github.com/scientist-softserv/adventist-dl/issues/624
> 🐛 Update webapp for public #solr_document

- .github/workflows/deploy.yaml
Disable the deploy to production option, until we're ready to go live with this app/repo. The host points to our current production domain. This is being done to prevent us from accidentally deploying to production until it's time to truly do so.
> :broom: disable production deploy option until we're ready

- Gemfile
- app/forms/hyrax/forms/admin/appearance_decorator.rb
In prod, Helvetica Neue is the default font, but in knapsack it was Nobile. The client has requested feature parity with prod.
Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/664
Related (Prod):
- https://github.com/scientist-softserv/adventist-dl/blob/7c2c64939044d61fd3a210e95fc3bcba761b79ae/app/forms/hyrax/forms/admin/appearance.rb#L14-L17
> i664 restore Helvetica Neue as the default font

- config/initializers/hyrax.rb
- config/locales/hyrax.en.yml
- ops/dev-deploy.tmpl.yaml
- ops/production-deploy.tmpl.yaml
- ops/staging-deploy.tmpl.yaml
Add missing translation for based_near label. Add geonames_username configuration to hyrax initializer to match production settings.
Issue
- https://github.com/scientist-softserv/adventist-dl/issues/693
Before this commit, the location does not load
After, the location field is a controlled vocabulary drop down with populated options.
> :bug: i693 - controlled vocab location dropdown does not load

- app/assets/stylesheets/adl-overrides/adl-overrides.scss
Collection show page text appears white with a text-shadow. The client wants feature parity with production, which is dark colored text and no text-shadow.
Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/724
> :broom: i724 - Update styling for collection show page

- config/initializers/sentry.rb
- hyku_knapsack.gemspec
- ops/dev-deploy.tmpl.yaml
- ops/production-deploy.tmpl.yaml
- ops/staging-deploy.tmpl.yaml
Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/633
sentry 
- https://scientist-inc.sentry.io/projects/adventist-knapsack/?project=4506742126673920
Docs
- https://docs.sentry.io/platforms/ruby/migration/
Test 
- `Sentry.capture_message("test", extra: { debug: true })`
- errors captured ✅ 
**Errors from UI automatically reports:** 
**Good job errors captured:**
> 🎁 i633 -  Set up sentry for adventist-knapsack servers

- app/assets/stylesheets/_bootstrap-default-overrides.scss
- app/assets/stylesheets/hyku_knapsack/application.scss
This commit will move the `bootstrap-default-overrides.scss` file to the root of the `app/assets/stylesheets` directory and import it directly.
> 🐛 Fix navbar breakpoint

- app/controllers/catalog_controller_decorator.rb
This commit brings back the implementation that allows the catalog search to sort by relevance.
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/129
> Restore sort by relevance for adventist

- docker-compose.yml
Adds env to app so that all services receive the variables. Also add a fits service to docker-compose.yml to remedy error: 
This prevents CharacterizeJob from running, making width and height nil.
> ⚙️ Set ENVs at APP level to propagate to WEB and WORKER

- app/models/ability_decorator.rb
we need to call to_param instead of id in order to properly find the solr docs.
> fix thumbnail permissions

- app/assets/stylesheets/adl-overrides/adl-overrides.scss
Displaying badges like "public" on the work and show pages was intentionally removed before the Knapsack cutover. Post cutover they were reintroduced. The client requests that they be removed again.
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/152
> update css to hide badges and tags

- app/assets/stylesheets/adl-overrides/adl-overrides.scss
We need a more specific class reference. We only want to hide the tags and badges from the titles.
ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/152
> :bug: Update class reference to hide title badges

- app/services/iiif_print/manifest_builder_service_behavior_decorator.rb
Some times we're seeing a file set come in with a nil mime type because something went wrong.  This would break the viewer because we get a `NoMethodError` when trying to call `include?`.  Adding the lonely operator here should prevent that from happening.
> 🐛 Add safe navigation operator for nil mime types

- app/models/bulkrax/csv_entry_decorator.rb
- app/parsers/bulkrax/csv_parser_decorator.rb
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/680
The client would import CSVs that had identifier columns, but the importer would still fail with "Missing at least one required element, missing element(s) are: identifier"
This commit utilizes the BOM method, previously created, and adds bom support for reading CSVs.
Download from [here](https://we.tl/t-GU29JxaNAD)
<details> 
</details> 
<details> 
</details>
> 🐛 Fix BOM bug round 2

- ops/staging-deploy.tmpl.yaml
Update the staging cluster issuer in the helm deploy values file to `wildcard-issuer`
This is live on production and persists the changes for the next deployment to staging.
- #699 
cert manager is not renewing certificates for staging automatically
cert manager is now renews certificates for staging automatically
<details>
<summary>Cert renewed</summary>
</details>
> Update the cert-manager cluster-issuer to wildcard-issuer

- .github/workflows/build-test-lint.yaml
- app/views/journal_articles/edit_fields/_date_created.html.erb
- app/views/records/edit_fields/_date_accepted.html.erb
- app/views/records/edit_fields/_date_available.html.erb
- app/views/records/edit_fields/_date_collected.html.erb
- app/views/records/edit_fields/_date_copyrighted.html.erb
- app/views/records/edit_fields/_date_created.html.erb
- app/views/records/edit_fields/_date_issued.html.erb
- app/views/records/edit_fields/_date_of_award.html.erb
- app/views/records/edit_fields/_date_published.html.erb
- app/views/records/edit_fields/_date_submitted.html.erb
- app/views/records/edit_fields/_date_updated.html.erb
- app/views/records/edit_fields/_date_valid.html.erb
- app/views/records/edit_fields/_default.html.erb
- app/views/records/edit_fields/_end_date.html.erb
- app/views/records/edit_fields/_event_date.html.erb
- app/views/records/edit_fields/_start_date.html.erb
A dev was unable to edit a resource without receiving an error from the partial. This PR updates the partials to handle resources and dog biscuit records.
Refs
- https://github.com/scientist-softserv/adventist_knapsack/issues/687
> :bug: Fix form for resoures

- app/presenters/adl/iiif_manifest_presenter_factory_decorator.rb
- lib/iiif_manifest/manifest_builder/canvas_builder_factory_decorator.rb
This fixes issues preventing universal viewer from building the manifest with the items.
Two issues were found:
1) `Hyrax.config.curation_concerns` does not include the Resource objects. It is comparing to `solr_doc.hydra_model` which is the full work type name so the work types never match for resources.  This is a concerning bug because it comes from IiifPrint, and it is logical that it would affect any resources in a valkyrized app using IiifPrint. 
2) The logic to prevent the tn.jpg files from displaying in the viewer broke because the presenter no longer responds to `label`.
Refs https://github.com/scientist-softserv/adventist_knapsack/issues/730
Manifest had no items so it was empty.
Manifest includes image files of both file sets and child works.
<details> …
> Fix manifest

- config/metadata/file_set_metadata.yaml
Import_url is needed in file_set metadata
> Add import url to fileset

- app/models/generic_work_resource_decorator.rb
- app/models/image_resource_decorator.rb
Refs 
- https://github.com/scientist-softserv/adventist_knapsack/issues/774
PDF files did not split for Image & GenericWork resources.
PDF files split into pages of the same model as the parent.
<details>
</details>
> Fix splitting for generic work and image resoures

- app/jobs/iiif_print/child_works_from_pdf_job_decorator.rb
- app/services/iiif_print/split_pdfs/adventist_pages_to_jpgs_splitter.rb
Refs
- https://github.com/scientist-softserv/adventist_knapsack/issues/779
If the original file has a .pdf suffix, IiifPrint split will be attempted.
PDFjs/UV feature flipper `use_iiif_print` will bypass splitting when set to PDFjs.
<details>
</details>
Adding the flag to the splitter allowed the jobs to run and fail because no images were split. Instead the flag was moved to the beginning of the job itself, allowing the process to stop before submitting any further jobs.
> Do not split if pdfjs flipper on

- app/assets/stylesheets/adl-overrides/adl-overrides.scss
🎁 Hide User Collection and Public tags
This commit hides the User Collection and Public tags from the public
collection show pages (admin dashbaord) and the catalog search results
page.
Ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/791
- `User Collection` and `Public` tags were visible on the collection show page
- `User Collection` and `Public` tags were visible on the catalog search results
- `User collection` and `Public` tags are not visible on the collection show page
- `User Collection` and `Public` tags are not visible on the catalog search results
The acceptance criteria was updated to include the `Public` tags as well as the `User Collection` tags. [Approved by Katharine in Slack](https://assaydepot.slack.com/archives/C0313NJV9PE/p1725913695951139).
> 🎁 Hide User Collection and Public tags

- app/assets/stylesheets/adl-overrides/adl-overrides.scss
🎁 Hide User Collection and Public tags
This commit expands on #795 to hides all tags from collection and works show pages. Additional tags were found in staging that will be removed by this commit.
Ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/791
- `User Collection` and `Public` tags were visible on collection and works show pages
- No `User collection` or `Public` are visible
The acceptance criteria is to match parity with the production application. There were additional tags found in staging that were removed by this commit.
> 🎁 Hides all badges to match parity with prod

- app/helpers/pdf_js_helper_decorator.rb
- app/views/hyrax/base/_pdf_js.erb
Sync Views PR broke some views. This restores functionality for pdf.js
> Fix pdf views

- app/models/concerns/hyrax/ability/resource_ability_decorator.rb
This commit overrides an ability mixin to check for either the slugs or id so when it's used downstream, we can ensure that the thumbnails are displaying correctly due to the permissions being set correctly.
> 🐛 Fix thumbnails not showing for logged out users

- app/views/hyrax/base/_attribute_rows.html.erb
- config/locales/dog_biscuits.en.yml
Updates metadata tag label for `date_issued` to display 'Date' on show and index pages.
Refs
- #169 
Date issued metadata tag displays 'Date issued'
Date issued metadata tag displays 'Date'
<details>
</details>
> Update date issued metadata tag label

- app/renderers/hyrax/renderers/attribute_renderer.rb
- config/metadata/adl_metadata.yaml
- config/metadata/collection_resource.yaml
- config/metadata/conference_item_resource.yaml
- config/metadata/dataset_resource.yaml
- config/metadata/exam_paper_resource.yaml
- config/metadata/generic_work_resource.yaml
- config/metadata/image_resource.yaml
- config/metadata/journal_article_resource.yaml
- config/metadata/published_work_resource.yaml
- config/metadata/thesis_resource.yaml
Blank metadata properties should not display on the show page for collections or works.
Refs
- https://github.com/scientist-softserv/adventist_knapsack/issues/771
Some metadata fields that did not have content were rending on the catalog page, the works show page, and the collection show page.
Only metadata fields that have content will render.
- Catalog page
- Works show page
- Collection show page
> Blank metadata fields

- lib/dog_biscuits/property_mappings/property_mappings.rb
This commit will update the deprecated link_to_search to link_to_facet which will enable the faceted properties on each search hit to be a link.
Ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/759
> 🐛 Update catalog search to fix discrepancies

- config/metadata/adl_metadata.yaml
- config/metadata/collection_resource.yaml
- config/metadata/conference_item_resource.yaml
- config/metadata/dataset_resource.yaml
- config/metadata/exam_paper_resource.yaml
- config/metadata/generic_work_resource.yaml
- config/metadata/image_resource.yaml
- config/metadata/journal_article_resource.yaml
- config/metadata/published_work_resource.yaml
- config/metadata/thesis_resource.yaml
This commit will check Adventist production's metadata for it's multiple and single values and compare it to Valkyrie's.  We spotted many differences and this commit aims to resolve them.
Ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/822
> 🐛 Fix metadata multiple or single

- app/controllers/catalog_controller_decorator.rb
This commit will add the index field for snippets onto the CatalogControllerDecorator so ADL can see snippets.  We had to add this because we remove all the add index fields prior and only add select ones.  That means we have to manually add this one.
Ref:
- https://github.com/scientist-softserv/adventist_knapsack/issues/769
> 🎁 Add snippets to catalog search

- config/metadata/collection_resource.yaml
Originally changed because it matches Adventist prior to Valkyrie, but it seems to be causing issues so I'm changing it to _tesim.
Ref https://github.com/scientist-softserv/adventist_knapsack/issues/822
> 🐛 Change indexing for issue_number

- config/metadata/adl_metadata.yaml
- config/metadata/collection_resource.yaml
- config/metadata/conference_item_resource.yaml
- config/metadata/dataset_resource.yaml
- config/metadata/exam_paper_resource.yaml
- config/metadata/generic_work_resource.yaml
- config/metadata/image_resource.yaml
- config/metadata/journal_article_resource.yaml
- config/metadata/published_work_resource.yaml
- config/metadata/thesis_resource.yaml
Metadata yaml files were audited and edited to:
- Change dates to be single rather than multiple
- Add multiple: false on form when term is not multiple... form defaults to multiple and term defaults to singular.
- Remove unnecessary state & arkivo_checksum
- remove dc_access_rights, which shares the same predicate in fedora with access_rights. (the shared predicate means they do the same thing, and the term is not accessed except in indexing.)
Refs
- https://github.com/scientist-softserv/adventist_knapsack/issues/777
- https://github.com/scientist-softserv/adventist_knapsack/issues/822
Many works types could be created but not edited.
Metadata single or multiple on form did not match production.
- All work types and collection can be created.
- All work types and collection can be …
> Clean up metadata issues

- lib/iiif_manifest/manifest_builder/canvas_builder_factory_decorator.rb
Expected term isn't always indexed. Adding a fallback to a different term to find file name.
Refs
- https://github.com/scientist-softserv/adventist_knapsack/issues/838
Older filesets without `original_filename_ssi` indexed show a black box for the universal viewer.
Universal viewer displays images.
<details>
</details>
> Viewer fails for older files

- app/views/themes/adventist_digital_library/layouts/hyrax.html.erb
Ref https://github.com/scientist-softserv/adventist_knapsack/issues/841
Add link to shared/modal in the layout for the adl theme.
Nothing happens when clicking "more>>" on the facets list.
Modal opens correctly.
<details>
</details>
> Fix "more>>" modal popup on facets

- .rubocop.yml
- app/indexers/conference_item_resource_indexer.rb
- app/indexers/dataset_resource_indexer.rb
- app/indexers/exam_paper_resource_indexer.rb
- app/indexers/generic_work_resource_indexer_decorator.rb
- app/indexers/image_resource_indexer_decorator.rb
- app/indexers/journal_article_resource_indexer.rb
- app/indexers/published_work_resource_indexer.rb
- app/indexers/sorted_date_indexer.rb
- app/indexers/thesis_resource_indexer.rb
This fixes the date range facet. ⚠️  Reindex is required ⚠️ 
Refs
- https://github.com/scientist-softserv/adventist_knapsack/issues/847
Date Range facet did not return any results
Data must have date_created, which is a use input field. 
﻿﻿
> I847 fix date range facet

- app/controllers/catalog_controller_decorator.rb
- app/forms/conference_item_resource_form.rb
- app/forms/dataset_resource_form.rb
- app/forms/exam_paper_resource_form.rb
- app/forms/journal_article_resource_form.rb
- app/forms/published_work_resource_form.rb
- app/forms/thesis_resource_form.rb
- app/models/conference_item_resource.rb
- app/models/dataset_resource.rb
- app/models/exam_paper_resource.rb
- app/models/journal_article_resource.rb
- app/models/published_work_resource.rb
- app/models/thesis_resource.rb
- app/views/hyrax/base/_attribute_rows.html.erb
- config/initializers/wings.rb
- config/metadata/adl_metadata.yaml
- config/metadata/basic_metadata.yaml
- config/metadata/collection_resource.yaml
- config/metadata/file_set_metadata.yaml
- config/metadata/generic_work_resource.yaml
- config/metadata/image_resource.yaml
Refs https://github.com/scientist-softserv/adventist_knapsack/issues/851
Using based near crashes the app.
Based Near attributes save, display, and edit appropriately
<details>
</details>
> Fix Based Near functionality

- app/controllers/catalog_controller_decorator.rb
- app/helpers/hyku_knapsack/application_helper.rb
- spec/helpers/hyku_knapsack/application_helper_spec.rb
Refs
- https://github.com/scientist-softserv/adventist_knapsack/issues/769
Snippets didn't work correctly
<details>
</details>
> Update Hyku to bring in snippets fixes

- config/initializers/pre_wings.rb
Re-define custom queries needed for slugs.
Definition was removed in https://github.com/scientist-softserv/adventist_knapsack/pull/859
App crashed trying to load catalog page, with `find_with_slug` undefined.
Able to create, view, and delete works with slugs.
<details>
<summary>Newly created work with slug</summary>
</details>
> Re-define custom queries

- app/helpers/pdf_js_helper_decorator.rb
- app/presenters/hyku/work_show_presenter_decorator.rb
Refs:
- #880 
- #881 
In the case of a split work, :pdf? needs to be included in the methods checked on a presenter.
In the case of a work that isn't split, Valkyrie has changed the term we use to check for a `.pdf` suffix. It appears that we do not fill in the label term. If characterization fails and we fall back to looking for a pdf, we needed to look in the right location.
When PDF.js is selected via flipper and a work has been split, it sometimes just shows a thumbnail.
When PDF.js is selected via flipper and work is not split, it sometimes just shows a thumbnail.
In new (valkyrie) resources, resources converted from Fedora, and works still in Fedora:
- When PDF.js is selected via flipper and a work has been split, it shows the UV
- When PDF.js is selected via flipper and a work is …
> Ensure that viewers show rather than thumbnails

- app/helpers/pdf_js_helper_decorator.rb
- app/presenters/hyku/work_show_presenter_decorator.rb
Removes some of custom logic for when to use universal viewer. Even if a work has been split to child works it now uses the pdf.js viewer if that is the setting.
Some overrides still exist, to allow the viewer to display for either a url or an attached file.
The pdf.js viewer retains the override to not respect the checkbox to not show the viewer. This is a problematic option, because it wasn't correctly initializing to checked in all cases. Until this can be resolved, the options are hidden.
Refs https://github.com/notch8/adventist_knapsack/issues/939
If a pdf is split into child works the Universal Viewer shows regardless of setting.
If pdf.js viewer is selected, the pdf.js viewer will show if the representative file is set to be the pdf. (This can be modified by editing the work). 
The …
> Use PDF.js

- app/presenters/hyrax/pcdm_member_presenter_factory_decorator.rb
In a number of cases, unmigrated works are showing a thumbnail rather than an image viewer. 
Old & unmigrated work shows a thumbnail, but shows viewer once migration happens.
No option to set/change a representative or thumbnail in the work's edit view.
Unmigrated works show appropriate viewer.
Able to update representative image & thumbnail on the work edit page.
<details>
<summary>Example work in staging</summary>
Previously showed only thumbnail image, with no option to change in edit.
https://adl.s2.adventistdigitallibrary.org/concern/published_works/f87149de-4e66-4f36-88d7-2a10a7cdd947
Before:
</details>
> Add fallback method to find filesets

- app/models/solr_document_decorator.rb
- app/presenters/hyrax/pcdm_member_presenter_factory_decorator.rb
Creating child works with slugs did not correctly build and display the works and relationships. Creating through the UI did not show the relationships, but creating through Bulkrax did not work at all.
Member relationships use the object's id. However the solr document is indexed with the slug as the id. We have to ensure that we search the appropriate terms in the solr document when we are searching by id.
This commit fixes two aspects of child works with slugs:
1. It ensures that a work can find its child works with slugs.
2. It ensures that a work with slugs can find its parent work.
This preparation is needed before [bulkrax relationship fixes](https://github.com/samvera/bulkrax/pull/1028) are incorporated into the application, as they would break the UI if they used slugs.
Note: The …
> Child works should be able to have slugs

- app/jobs/application_job_decorator.rb
By default, the Hyrax::QueuedIndexingJob is set to a priority of 0. Along with the number of jobs handled before rescheduling and the delay between jobs, this can result in the queue getting too backed up.
Upping the priority higher than the migration jobs lets the indexing jobs jump ahead and prevents them from getting stuck behind the migration jobs which were scheduled earlier.
> Up job priority for Hyrax::QueuedIndexingJob

- .gitmodules
Refs https://github.com/samvera/hyku/pull/2538
Queued indexing failed on a Bulkrax import due to the work failing to find the file set in solr. 
Indexing job failed when worker uses queued indexing. Bulkrax ingest appeared to complete normally but work is not accessible in the UI because work and file set are not indexed. File set and then work had to be indexed manually.
Bulkrax ingest completes normally.
> Submodule update for queued-indexer testing

- app/controllers/catalog_controller_decorator.rb
- config/locales/blacklight.en.yml
- docker-compose.yml
- spec/controllers/catalog_controller_decorator_spec.rb
Refs https://github.com/notch8/adventist_knapsack/issues/905
Removes dog biscuits definition of terms showing on the catalog page, and defines them explicitly in the catalog controller decorator.
Adds missing translations for the new terms to the locale file.
Sets flexible off for dev environment.
Clicking on a faceted item displayed the catalog page rather than a faceted search.
- Catalog facets for items appropriately do a faceted search
<details>
<summary>Catalog Page</summary>
[recorded (20).webm](https://github.com/user-attachments/assets/40c8a5c2-8d00-4419-b6f9-04699752bf57)
</details>
> Catalog page faceted search

- config/metadata/collection_resource.yaml
- spec/search_builders/adv_search_builder_spec.rb
This commit updates the submodule that will add the ability to exclude a collection from the catalog search results.
A checkbox to `Hide from catalog search` is added to the Discovery tab of the collection edit form. Checking the box will set the `hide_from_catalog_search` attribute on the CollectionResource to true which will filter it from the search results.
The `hide_from_catalog_search` attribute is added to the collection resource metadata.
Ref:
- https://github.com/notch8/adventist_knapsack/issues/892
> 🎁 Exclude collection from catalog search results
