- app/forms/hyrax/generic_work_form_decorator.rb
- app/forms/hyrax/image_form_decorator.rb
- app/forms/hyrax/journal_article_form.rb
- app/models/conference_item.rb
- app/models/dataset.rb
- app/models/exam_paper.rb
- app/models/generic_work_decorator.rb
- app/models/image_decorator.rb
- app/models/journal_article.rb
- app/models/published_work.rb
- app/models/thesis.rb
- app/views/journal_articles/edit_fields/_date_created.html.erb
- config/initializers/hyrax.rb
- config/initializers/knapsack_authorities.rb
- lib/dog_biscuits/configuration.rb
- lib/dog_biscuits/indexers/concerns/indexes_common.rb
We should be able to create each of the following work types, from the UI: 
Refs 
- https://github.com/scientist-softserv/adventist-dl/issues/564
<details>
<summary>Conference Item</summary>
</details>
<details>
<summary>Dataset</summary>
</details>
<details>
<summary>Exam Paper</summary>
</details>
<details>
<summary>Journal Article</summary>
</details>
<details>
<summary>Published Work</summary>
</details>
<details>
<summary>Thesis</summary>
</details>
<details>
<summary>Generic Work</summary>
</details>
<details>
<summary>Image</summary>
</details>
> I564 create various work types

- Gemfile
- app/forms/hyrax/form_terms_decorator.rb
- app/presenters/hyrax/collection_presenter_decorator.rb
- app/presenters/hyrax/generic_work_presenter_decorator.rb
- lib/tasks/assets.rake
- spec/factories/works.rb
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/538
> 🧹 Appease Rubocop

- .github/PULL_REQUEST_TEMPLATE.md
By using a bullet point, Github unfurls the text of the link.
> 🧹 Favor bullet point for issuenumber

- app/controllers/catalog_controller_decorator.rb
- spec/controllers/catalog_controller_decorator_spec.rb
Due to load priorities, we should verify the
CatalogController.search_builder_class
> 🧹 Verify CatalogController.search_builder_class

- app/views/_user_util_links.html.erb
This is changes that are in Hyku but not Adventist.  Trying to remove the differences.
> 🧹 Add aria-controls specifier

- lib/hyku_knapsack/engine.rb
- spec/hyku_knapsack/engine_spec.rb
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/492
- https://github.com/scientist-softserv/adventist-dl/issues/618
- https://github.com/samvera/hyku/pull/1964
- https://github.com/scientist-softserv/adventist-dl/pull/493
- https://github.com/samvera/hyku/pull/2020
> ♻️ Ensure users cannot register on their own

- README.md
Minor tweak
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/552
> 📚 Update readme for bin/knapsacker

- app/controllers/catalog_controller_decorator.rb
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/630
> 🐛 Render source as link (when link-ish)

- Dockerfile
Assets were not building in the right order. Now they should include assets from the knapsack
> fix asset building

- app/services/iiif_print/manifest_builder_service_behavior_decorator.rb
- lib/hyku_knapsack/engine.rb
- spec/config/initializers/iiif_print_spec.rb
With Knapsack, we're noticing that load path issues can be a subtle
problem.
With this commit, I'm testing the configuration to ensure that we have
the expected and correct lamba for generating IIIF Page's file titles.
Related to:
- https://github.com/scientist-softserv/adventist-dl/issues/628
> ☑️ Add test to clarify expected configuration

- ops/staging-deploy.tmpl.yaml
Errors seen in staging when running an importer seems to be related to missing env variables:
> Update staging-deploy.tmpl.yaml env variables

- Gemfile.lock
- app/views/hyrax/base/show.html.erb
Action buttons were missing post knapsack deploy to prod
Issue:
- https://github.com/scientist-softserv/adventist-dl/issues/747
> 🐛 Restore action buttons

- config/locales/hyrax.en.yml
- config/metadata/collection_resource.yaml
Issue:
- https://github.com/scientist-softserv/adventist_knapsack/issues/777
- Adds department property to CollectionResource
- Adds a locale label for department.
> :broom: [i777] - Collection metadata clean up

- bin/db-migrate-seed.sh
Previous version of this script did not handle engine migrations and would get the wrong count pretty easily.
> move seed script to ruby, make it more responsive to db changes

- config/initializers/iiif_print.rb
related: 
- https://github.com/scientist-softserv/iiif_print/pull/375
Issue: 
- https://github.com/scientist-softserv/adventist_knapsack/issues/856
> ⚙️ Configure image magic resources for iiif_print

- app/jobs/iiif_print/child_works_from_pdf_job_decorator.rb
Fixes code changed rapidly for production deploy errors.
<details>
</details>
> Fix rubocop complaint

- ops/production-deploy.tmpl.yaml
These variables are present in staging but missing in prod, which may be the cause for decrepancies.
> Update prod deploy env vars

- config/metadata/adl_metadata.yaml
- config/metadata/generic_work_resource.yaml
- config/metadata/image_resource.yaml
Rights statement cannot be true for migrations to work. 
<details>
</details>
> Remove requirement for Rights Statement

- app/controllers/catalog_controller_decorator.rb
Title should always be included when searching all fields, even if it isn't configured as a show field.
Ref:
- https://github.com/notch8/palni_palci_knapsack/issues/288
- https://github.com/notch8/palni_palci_knapsack/pull/312
> Ensure title is included when searching all fields

- db/migrate/20250312193045_add_another_slug_index_valkyrie.rb
- lib/good_jobs/jobs_decorator.rb
- Shaved every Valkyrie object look up by slug down substantially (from 1-2 S for a full table look up to 4-6ms)
- Added a method to GoodJob::Job -> `GoodJob::Job.completed_jobs_statistics(start_at: 1.day.ago, end_at: Time.now)` to get the last days average completion time by job class
> Migration performance

- .github/workflows/build-test-lint.yaml
Fix requeueing and rack-attack issue with collection pages
> bump hyrax

- Dockerfile
- bundler.d/example.rb
- docker-compose.yml
> Pin hyrax version to pull in chunk upload fix
